# Generated by Django 5.1.3 on 2024-11-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('kilometers', models.IntegerField()),
                ('gender', models.BooleanField(choices=[('male', 'Male'), ('female', 'Female')])),
            ],
        ),
    ]
