# Generated by Django 5.1.3 on 2024-11-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='gender',
            field=models.BooleanField(choices=[('Male', 'Male'), ('Memale', 'Female')]),
        ),
    ]
