# Generated by Django 5.1.3 on 2024-11-17 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_events_date_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Event_SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Id_pic', models.ImageField(upload_to='Id_image/')),
                ('bime', models.ImageField(upload_to='bime_image/')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100)),
                ('category', models.TextField(choices=[('zir_35', 'zir_35'), ('Female', 'Female')])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
            ],
        ),
    ]
