# Generated by Django 5.1.3 on 2024-11-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_events_status_alter_events_date_time_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_signup',
            name='bime',
        ),
        migrations.RemoveField(
            model_name='event_signup',
            name='email',
        ),
        migrations.AddField(
            model_name='event_signup',
            name='insurance_pic',
            field=models.ImageField(blank=True, upload_to='insurance_image/', verbose_name='Insurance Picture'),
        ),
        migrations.AlterField(
            model_name='event_signup',
            name='Id_pic',
            field=models.ImageField(upload_to='Id_image/', verbose_name='Id Picture'),
        ),
        migrations.AlterField(
            model_name='event_signup',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='event_signup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='event_signup',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='Phone Number'),
        ),
    ]
