# Generated by Django 5.1.3 on 2024-11-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_signup_bime_remove_event_signup_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_signup',
            name='insurance_pic',
            field=models.ImageField(upload_to='insurance_image/', verbose_name='Insurance Picture'),
        ),
    ]
