# Generated by Django 5.1.3 on 2024-11-20 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_event_signup_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
