# Generated by Django 5.1.3 on 2024-11-21 14:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_events_date_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='second_image',
            field=models.ImageField(upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='title_image',
            field=models.ImageField(upload_to='event_images/'),
        ),
    ]
