# Generated by Django 5.1.3 on 2024-11-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_events_description_alter_events_second_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_signup',
            name='paid_pic',
            field=models.ImageField(blank=True, upload_to='paid_image/', verbose_name='Paid Picture'),
        ),
    ]
