# Generated by Django 5.0.9 on 2024-11-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_event_signup_paid_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_signup',
            name='category',
            field=models.TextField(choices=[('زیر ۱۸', 'زیر ۱۸'), ('18 ta 40', '18 ta 40'), ('40 ta 45', '40 ta 45'), ('45 bala', '45 bala')], verbose_name='category'),
        ),
    ]
