# Generated by Django 5.0.9 on 2024-11-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_event_signup_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_signup',
            name='category',
            field=models.TextField(choices=[('زیر ۱۸', 'زیر ۱۸ ,  '), ('18 ta 40', '18 ta 40'), ('40 ta 45', '40 ta 45'), ('45 bala', '45 bala')], verbose_name='category'),
        ),
    ]
