# Generated by Django 5.0.9 on 2024-11-24 09:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sponsers_image/')),
                ('link', models.URLField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='our_mission',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='whatis_runclub',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
